# Generated by Django 4.2 on 2023-04-10 14:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="data_joined",
            new_name="date_joined",
        ),
    ]
