# Generated by Django 4.2 on 2023-04-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="cover_photo",
            field=models.ImageField(
                blank=True,
                default="cover_default.jpg",
                null=True,
                upload_to="users/cover_photos",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="default_user.jpg",
                null=True,
                upload_to="users/profile_picture",
            ),
        ),
    ]
