# Generated by Django 4.2 on 2023-04-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_alter_userprofile_cover_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="default_user.jpg",
                null=True,
                upload_to="users/profile_pictures",
            ),
        ),
    ]
